### ISSUE TITLE
[TODO] Preparation for the publication

### ISSUE THREAD

**Issue by nissymori** [nissymori/JAX-CORL#42]
# 体裁を合わせよう

全て性能が下がらないことを確認しながらいこうな．
### モデル
- [x] MLPを今のCQLに合わせよう
- [ ] `ensemblize`を廃止して`Double critic`にしよう！
- [x] `TanhPolicy`に統一しよう.
- [x] `TD3BC`の`target_critic_params`やめよう
- [x] `hidden_dims`に統一しよう

### データの前処理
- [x] stateのnormalizeするかどうか統一しよう
- [x] rewardのnormalizeするかどうか統一しよう

### 変数名関数名統一しよう
- [x] `tau`, `polyak`
- [x] `gamma`, `discount`
- [x] `key`, `rng`
- [x] `critic_def`, `critic_model`
- [x] `dones_float`, `dones`, `mask`
- [x] `states`, `observations`

### 型を表記しよう
- [x] awac
- [ ] cql
- [x] iql
- [x] td3bc

### コメントを丁寧に書こう
- [x] awac
- [x] cql
- [ ] iql
- [x] td3bc

### Configもう少し考えよう
- [x] awac
- [x] cql
- [x] iql
- [x] td3bc

# シンプルに性能をあげよう
- CQL
    - [ ] [CORL](https://github.com/tinkoff-ai/CORL/tree/main), [JaxCQL](https://github.com/young-geng/JaxCQL/blob/master/JaxCQL/conservative_sac.py#L26) などと比較
    - [ ] 実装
    - [ ] eval
- AWAC
    - [ ] [CORL](https://github.com/tinkoff-ai/CORL/tree/main)などと比較
    - [ ] 実装
    - [ ] eval

# report
- [x] script
- [x] wandb

# 公開に向けた雑務
- [x] requrements.txt
- [x] make file
- [x] ライセンス
